### ISSUE TITLE
Unable to install with Symfony 4.1.0

### ISSUE THREAD

**Issue by lfjeff** [nerds-and-company/css-to-inline-styles-twig-extension#3]
Got a bunch of errors when I tried to install with the latest version of Symfony...

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install nerds-and-company/css-to-inline-styles-twig-extension 1.1.1
    - Conclusion: remove symfony/http-kernel v4.1.0
    - Conclusion: don't install symfony/http-kernel v4.1.0
    - twig/twig 1.3.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig 1.4.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig 1.5.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig 1.5.1 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig 1.6.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig 1.6.1 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig 1.6.2 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig 1.6.3 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig 1.6.4 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig 1.6.5 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.10.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.10.1 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.10.2 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.10.3 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.11.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.11.1 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.12.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.12.1 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.12.2 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.12.3 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.13.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.13.1 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.13.2 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.14.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.14.1 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.14.2 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.15.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.15.1 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.16.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.16.1 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.16.2 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.16.3 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.17.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.18.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.18.1 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.18.2 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.19.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.20.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.21.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.21.1 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.21.2 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.22.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.22.1 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.22.2 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.22.3 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.23.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.23.1 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.23.2 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.23.3 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.24.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.24.1 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.24.2 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.25.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.26.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.26.1 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.27.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.28.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.28.1 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.28.2 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.29.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.30.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.31.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.32.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.33.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.33.1 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.33.2 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.7.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.8.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.8.1 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.8.2 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.8.3 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.9.0 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.9.1 conflicts with symfony/http-kernel[v4.1.0].
    - twig/twig v1.9.2 conflicts with symfony/http-kernel[v4.1.0].
    - Conclusion: don't install twig/twig v2.4.8|install twig/twig 1.3.0|install twig/twig 1.4.0|install twig/twig 1.5.0|install twig/twig 1.5.1|install twig/twig 1.6.0|install twig/twig 1.6.1|install twig/twig 1.6.2|install twig/twig 1.6.3|install twig/twig 1.6.4|install twig/twig 1.6.5|install twig/twig v1.10.0|install twig/twig v1.10.1|install twig/twig v1.10.2|install twig/twig v1.10.3|install twig/twig v1.11.0|install twig/twig v1.11.1|install twig/twig v1.12.0|install twig/twig v1.12.1|install twig/twig v1.12.2|install twig/twig v1.12.3|install twig/twig v1.13.0|install twig/twig v1.13.1|install twig/twig v1.13.2|install twig/twig v1.14.0|install twig/twig v1.14.1|install twig/twig v1.14.2|install twig/twig v1.15.0|install twig/twig v1.15.1|install twig/twig v1.16.0|install twig/twig v1.16.1|install twig/twig v1.16.2|install twig/twig v1.16.3|install twig/twig v1.17.0|install twig/twig v1.18.0|install twig/twig v1.18.1|install twig/twig v1.18.2|install twig/twig v1.19.0|install twig/twig v1.20.0|install twig/twig v1.21.0|install twig/twig v1.21.1|install twig/twig v1.21.2|install twig/twig v1.22.0|install twig/twig v1.22.1|install twig/twig v1.22.2|install twig/twig v1.22.3|install twig/twig v1.23.0|install twig/twig v1.23.1|install twig/twig v1.23.2|install twig/twig v1.23.3|install twig/twig v1.24.0|install twig/twig v1.24.1|install twig/twig v1.24.2|install twig/twig v1.25.0|install twig/twig v1.26.0|install twig/twig v1.26.1|install twig/twig v1.27.0|install twig/twig v1.28.0|install twig/twig v1.28.1|install twig/twig v1.28.2|install twig/twig v1.29.0|install twig/twig v1.30.0|install twig/twig v1.31.0|install twig/twig v1.32.0|install twig/twig v1.33.0|install twig/twig v1.33.1|install twig/twig v1.33.2|install twig/twig v1.7.0|install twig/twig v1.8.0|install twig/twig v1.8.1|install twig/twig v1.8.2|install twig/twig v1.8.3|install twig/twig v1.9.0|install twig/twig v1.9.1|install twig/twig v1.9.2
    - Conclusion: don't install nerds-and-company/css-to-inline-styles-twig-extension 1.1.1|remove twig/twig v2.4.8|install twig/twig 1.3.0|install twig/twig 1.4.0|install twig/twig 1.5.0|install twig/twig 1.5.1|install twig/twig 1.6.0|install twig/twig 1.6.1|install twig/twig 1.6.2|install twig/twig 1.6.3|install twig/twig 1.6.4|install twig/twig 1.6.5|install twig/twig v1.10.0|install twig/twig v1.10.1|install twig/twig v1.10.2|install twig/twig v1.10.3|install twig/twig v1.11.0|install twig/twig v1.11.1|install twig/twig v1.12.0|install twig/twig v1.12.1|install twig/twig v1.12.2|install twig/twig v1.12.3|install twig/twig v1.13.0|install twig/twig v1.13.1|install twig/twig v1.13.2|install twig/twig v1.14.0|install twig/twig v1.14.1|install twig/twig v1.14.2|install twig/twig v1.15.0|install twig/twig v1.15.1|install twig/twig v1.16.0|install twig/twig v1.16.1|install twig/twig v1.16.2|install twig/twig v1.16.3|install twig/twig v1.17.0|install twig/twig v1.18.0|install twig/twig v1.18.1|install twig/twig v1.18.2|install twig/twig v1.19.0|install twig/twig v1.20.0|install twig/twig v1.21.0|install twig/twig v1.21.1|install twig/twig v1.21.2|install twig/twig v1.22.0|install twig/twig v1.22.1|install twig/twig v1.22.2|install twig/twig v1.22.3|install twig/twig v1.23.0|install twig/twig v1.23.1|install twig/twig v1.23.2|install twig/twig v1.23.3|install twig/twig v1.24.0|install twig/twig v1.24.1|install twig/twig v1.24.2|install twig/twig v1.25.0|install twig/twig v1.26.0|install twig/twig v1.26.1|install twig/twig v1.27.0|install twig/twig v1.28.0|install twig/twig v1.28.1|install twig/twig v1.28.2|install twig/twig v1.29.0|install twig/twig v1.30.0|install twig/twig v1.31.0|install twig/twig v1.32.0|install twig/twig v1.33.0|install twig/twig v1.33.1|install twig/twig v1.33.2|install twig/twig v1.7.0|install twig/twig v1.8.0|install twig/twig v1.8.1|install twig/twig v1.8.2|install twig/twig v1.8.3|install twig/twig v1.9.0|install twig/twig v1.9.1|install twig/twig v1.9.2
    - Conclusion: don't install nerds-and-company/css-to-inline-styles-twig-extension 1.1.1|don't install twig/twig v2.4.8|install twig/twig 1.3.0|install twig/twig 1.4.0|install twig/twig 1.5.0|install twig/twig 1.5.1|install twig/twig 1.6.0|install twig/twig 1.6.1|install twig/twig 1.6.2|install twig/twig 1.6.3|install twig/twig 1.6.4|install twig/twig 1.6.5|install twig/twig v1.10.0|install twig/twig v1.10.1|install twig/twig v1.10.2|install twig/twig v1.10.3|install twig/twig v1.11.0|install twig/twig v1.11.1|install twig/twig v1.12.0|install twig/twig v1.12.1|install twig/twig v1.12.2|install twig/twig v1.12.3|install twig/twig v1.13.0|install twig/twig v1.13.1|install twig/twig v1.13.2|install twig/twig v1.14.0|install twig/twig v1.14.1|install twig/twig v1.14.2|install twig/twig v1.15.0|install twig/twig v1.15.1|install twig/twig v1.16.0|install twig/twig v1.16.1|install twig/twig v1.16.2|install twig/twig v1.16.3|install twig/twig v1.17.0|install twig/twig v1.18.0|install twig/twig v1.18.1|install twig/twig v1.18.2|install twig/twig v1.19.0|install twig/twig v1.20.0|install twig/twig v1.21.0|install twig/twig v1.21.1|install twig/twig v1.21.2|install twig/twig v1.22.0|install twig/twig v1.22.1|install twig/twig v1.22.2|install twig/twig v1.22.3|install twig/twig v1.23.0|install twig/twig v1.23.1|install twig/twig v1.23.2|install twig/twig v1.23.3|install twig/twig v1.24.0|install twig/twig v1.24.1|install twig/twig v1.24.2|install twig/twig v1.25.0|install twig/twig v1.26.0|install twig/twig v1.26.1|install twig/twig v1.27.0|install twig/twig v1.28.0|install twig/twig v1.28.1|install twig/twig v1.28.2|install twig/twig v1.29.0|install twig/twig v1.30.0|install twig/twig v1.31.0|install twig/twig v1.32.0|install twig/twig v1.33.0|install twig/twig v1.33.1|install twig/twig v1.33.2|install twig/twig v1.7.0|install twig/twig v1.8.0|install twig/twig v1.8.1|install twig/twig v1.8.2|install twig/twig v1.8.3|install twig/twig v1.9.0|install twig/twig v1.9.1|install twig/twig v1.9.2
    - Installation request for symfony/http-kernel (locked at v4.1.0) -> satisfiable by symfony/http-kernel[v4.1.0].
    - Conclusion: don't install nerds-and-company/css-to-inline-styles-twig-extension 1.1.1|remove twig/twig v2.4.8|install twig/twig 1.3.0|install twig/twig 1.4.0|install twig/twig 1.5.0|install twig/twig 1.5.1|install twig/twig 1.6.0|install twig/twig 1.6.1|install twig/twig 1.6.2|install twig/twig 1.6.3|install twig/twig 1.6.4|install twig/twig 1.6.5|install twig/twig v1.10.0|install twig/twig v1.10.1|install twig/twig v1.10.2|install twig/twig v1.10.3|install twig/twig v1.11.0|install twig/twig v1.11.1|install twig/twig v1.12.0|install twig/twig v1.12.1|install twig/twig v1.12.2|install twig/twig v1.12.3|install twig/twig v1.13.0|install twig/twig v1.13.1|install twig/twig v1.13.2|install twig/twig v1.14.0|install twig/twig v1.14.1|install twig/twig v1.14.2|install twig/twig v1.15.0|install twig/twig v1.15.1|install twig/twig v1.16.0|install twig/twig v1.16.1|install twig/twig v1.16.2|install twig/twig v1.16.3|install twig/twig v1.17.0|install twig/twig v1.18.0|install twig/twig v1.18.1|install twig/twig v1.18.2|install twig/twig v1.19.0|install twig/twig v1.20.0|install twig/twig v1.21.0|install twig/twig v1.21.1|install twig/twig v1.21.2|install twig/twig v1.22.0|install twig/twig v1.22.1|install twig/twig v1.22.2|install twig/twig v1.22.3|install twig/twig v1.23.0|install twig/twig v1.23.1|install twig/twig v1.23.2|install twig/twig v1.23.3|install twig/twig v1.24.0|install twig/twig v1.24.1|install twig/twig v1.24.2|install twig/twig v1.25.0|install twig/twig v1.26.0|install twig/twig v1.26.1|install twig/twig v1.27.0|install twig/twig v1.28.0|install twig/twig v1.28.1|install twig/twig v1.28.2|install twig/twig v1.29.0|install twig/twig v1.30.0|install twig/twig v1.31.0|install twig/twig v1.32.0|install twig/twig v1.33.0|install twig/twig v1.33.1|install twig/twig v1.33.2|install twig/twig v1.7.0|install twig/twig v1.8.0|install twig/twig v1.8.1|install twig/twig v1.8.2|install twig/twig v1.8.3|install twig/twig v1.9.0|install twig/twig v1.9.1|install twig/twig v1.9.2
    - Conclusion: don't install nerds-and-company/css-to-inline-styles-twig-extension 1.1.1|don't install twig/twig v2.4.8|install twig/twig 1.3.0|install twig/twig 1.4.0|install twig/twig 1.5.0|install twig/twig 1.5.1|install twig/twig 1.6.0|install twig/twig 1.6.1|install twig/twig 1.6.2|install twig/twig 1.6.3|install twig/twig 1.6.4|install twig/twig 1.6.5|install twig/twig v1.10.0|install twig/twig v1.10.1|install twig/twig v1.10.2|install twig/twig v1.10.3|install twig/twig v1.11.0|install twig/twig v1.11.1|install twig/twig v1.12.0|install twig/twig v1.12.1|install twig/twig v1.12.2|install twig/twig v1.12.3|install twig/twig v1.13.0|install twig/twig v1.13.1|install twig/twig v1.13.2|install twig/twig v1.14.0|install twig/twig v1.14.1|install twig/twig v1.14.2|install twig/twig v1.15.0|install twig/twig v1.15.1|install twig/twig v1.16.0|install twig/twig v1.16.1|install twig/twig v1.16.2|install twig/twig v1.16.3|install twig/twig v1.17.0|install twig/twig v1.18.0|install twig/twig v1.18.1|install twig/twig v1.18.2|install twig/twig v1.19.0|install twig/twig v1.20.0|install twig/twig v1.21.0|install twig/twig v1.21.1|install twig/twig v1.21.2|install twig/twig v1.22.0|install twig/twig v1.22.1|install twig/twig v1.22.2|install twig/twig v1.22.3|install twig/twig v1.23.0|install twig/twig v1.23.1|install twig/twig v1.23.2|install twig/twig v1.23.3|install twig/twig v1.24.0|install twig/twig v1.24.1|install twig/twig v1.24.2|install twig/twig v1.25.0|install twig/twig v1.26.0|install twig/twig v1.26.1|install twig/twig v1.27.0|install twig/twig v1.28.0|install twig/twig v1.28.1|install twig/twig v1.28.2|install twig/twig v1.29.0|install twig/twig v1.30.0|install twig/twig v1.31.0|install twig/twig v1.32.0|install twig/twig v1.33.0|install twig/twig v1.33.1|install twig/twig v1.33.2|install twig/twig v1.7.0|install twig/twig v1.8.0|install twig/twig v1.8.1|install twig/twig v1.8.2|install twig/twig v1.8.3|install twig/twig v1.9.0|install twig/twig v1.9.1|install twig/twig v1.9.2
    - Installation request for nerds-and-company/css-to-inline-styles-twig-extension ^1.1 -> satisfiable by nerds-and-company/css-to-inline-styles-twig-extension[1.1.0, 1.1.1].
    - Conclusion: remove twig/twig v2.4.8|install twig/twig 1.3.0|install twig/twig 1.4.0|install twig/twig 1.5.0|install twig/twig 1.5.1|install twig/twig 1.6.0|install twig/twig 1.6.1|install twig/twig 1.6.2|install twig/twig 1.6.3|install twig/twig 1.6.4|install twig/twig 1.6.5|install twig/twig v1.10.0|install twig/twig v1.10.1|install twig/twig v1.10.2|install twig/twig v1.10.3|install twig/twig v1.11.0|install twig/twig v1.11.1|install twig/twig v1.12.0|install twig/twig v1.12.1|install twig/twig v1.12.2|install twig/twig v1.12.3|install twig/twig v1.13.0|install twig/twig v1.13.1|install twig/twig v1.13.2|install twig/twig v1.14.0|install twig/twig v1.14.1|install twig/twig v1.14.2|install twig/twig v1.15.0|install twig/twig v1.15.1|install twig/twig v1.16.0|install twig/twig v1.16.1|install twig/twig v1.16.2|install twig/twig v1.16.3|install twig/twig v1.17.0|install twig/twig v1.18.0|install twig/twig v1.18.1|install twig/twig v1.18.2|install twig/twig v1.19.0|install twig/twig v1.20.0|install twig/twig v1.21.0|install twig/twig v1.21.1|install twig/twig v1.21.2|install twig/twig v1.22.0|install twig/twig v1.22.1|install twig/twig v1.22.2|install twig/twig v1.22.3|install twig/twig v1.23.0|install twig/twig v1.23.1|install twig/twig v1.23.2|install twig/twig v1.23.3|install twig/twig v1.24.0|install twig/twig v1.24.1|install twig/twig v1.24.2|install twig/twig v1.25.0|install twig/twig v1.26.0|install twig/twig v1.26.1|install twig/twig v1.27.0|install twig/twig v1.28.0|install twig/twig v1.28.1|install twig/twig v1.28.2|install twig/twig v1.29.0|install twig/twig v1.30.0|install twig/twig v1.31.0|install twig/twig v1.32.0|install twig/twig v1.33.0|install twig/twig v1.33.1|install twig/twig v1.33.2|install twig/twig v1.7.0|install twig/twig v1.8.0|install twig/twig v1.8.1|install twig/twig v1.8.2|install twig/twig v1.8.3|install twig/twig v1.9.0|install twig/twig v1.9.1|install twig/twig v1.9.2
    - nerds-and-company/css-to-inline-styles-twig-extension 1.1.0 requires twig/twig ~1.0 -> satisfiable by twig/twig[1.3.0, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, v1.10.0, v1.10.1, v1.10.2, v1.10.3, v1.11.0, v1.11.1, v1.12.0, v1.12.1, v1.12.2, v1.12.3, v1.13.0, v1.13.1, v1.13.2, v1.14.0, v1.14.1, v1.14.2, v1.15.0, v1.15.1, v1.16.0, v1.16.1, v1.16.2, v1.16.3, v1.17.0, v1.18.0, v1.18.1, v1.18.2, v1.19.0, v1.20.0, v1.21.0, v1.21.1, v1.21.2, v1.22.0, v1.22.1, v1.22.2, v1.22.3, v1.23.0, v1.23.1, v1.23.2, v1.23.3, v1.24.0, v1.24.1, v1.24.2, v1.25.0, v1.26.0, v1.26.1, v1.27.0, v1.28.0, v1.28.1, v1.28.2, v1.29.0, v1.30.0, v1.31.0, v1.32.0, v1.33.0, v1.33.1, v1.33.2, v1.34.0, v1.34.1, v1.34.2, v1.34.3, v1.34.4, v1.35.0, v1.35.1, v1.35.2, v1.35.3, v1.35.4, v1.7.0, v1.8.0, v1.8.1, v1.8.2, v1.8.3, v1.9.0, v1.9.1, v1.9.2].
    - Can only install one of: twig/twig[v1.34.0, v2.4.8].
    - Can only install one of: twig/twig[v1.34.1, v2.4.8].
    - Can only install one of: twig/twig[v1.34.2, v2.4.8].
    - Can only install one of: twig/twig[v1.34.3, v2.4.8].
    - Can only install one of: twig/twig[v1.34.4, v2.4.8].
    - Can only install one of: twig/twig[v1.35.0, v2.4.8].
    - Can only install one of: twig/twig[v1.35.1, v2.4.8].
    - Can only install one of: twig/twig[v1.35.2, v2.4.8].
    - Can only install one of: twig/twig[v1.35.3, v2.4.8].
    - Can only install one of: twig/twig[v1.35.4, v2.4.8].
    - Installation request for twig/twig (locked at v2.4.8) -> satisfiable by twig/twig[v2.4.8].

Installation failed, reverting ./composer.json to its original content.

**Comment by bvangennep** [comment]
Should be resolved
