### ISSUE TITLE
Symfony 4.2; Expected type 'Twig\Extension\ExtensionInterface'

### ISSUE THREAD

**Issue by MartinMa** [nerds-and-company/css-to-inline-styles-twig-extension#6]
I get the following error (IDE is complaining), when calling `$this->twig->addExtension(new InlineCssExtension());`:

```
Expected type 'Twig\Extension\ExtensionInterface'. Found 'NerdsAndCompany\CssToInlineStyles\Twig\InlineCssExtension'.
```
I'm using Symfony 4.2 along with `"symfony/twig-bundle": "4.2.*"`. It is actually using twig `v2.9.0` I think.

Maybe the implementation interface for extensions has changed?

**Comment by bvangennep** [comment]
Probably fixed by #7 
Sorry, a bit late
